[APP_SETTINGS]
APP_NAME = "DataVisualization"
LOG_PATH = "DataVisualization.log"
LOG_LEVEL = "LogLevel.DEBUG"
APP_PATH = ""
EXCEL_CONTEXT = ""
SAMPLE_PROMPT_WITH_INSTRUCTIONS=""


[AZURE_CONFIG]
AZURE_DEPLOYMENT = ""
API_VERSION = ""
AZURE_ENDPOINT = ""
API_KEY = ""
MODEL = ""
TEMPERATURE = ""
STREAMING = ""


